//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAccountant.DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class debt_Transactions
    {
        public int Id { get; set; }
        public int DebtOperationId { get; set; }
        public double Sum { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual debt_DebtOperations debt_DebtOperations { get; set; }
    }
}
