//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAccountant.DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class debt_DebtOperations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public debt_DebtOperations()
        {
            this.debt_Transactions = new HashSet<debt_Transactions>();
        }
    
        public int Id { get; set; }
        public int AgentId { get; set; }
        public int UserId { get; set; }
        public int DebtTypeId { get; set; }
        public double StartSum { get; set; }
        public double RewardSum { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int CurrencyId { get; set; }
        public string Comment { get; set; }
        public bool IsInProgress { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual debt_DebtAgent debt_DebtAgent { get; set; }
        public virtual debt_DebtType debt_DebtType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debt_Transactions> debt_Transactions { get; set; }
    }
}
