//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAccountant.DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class other_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public other_Projects()
        {
            this.other_FreelancePayement = new HashSet<other_FreelancePayement>();
            this.other_SpendHoursPerProject = new HashSet<other_SpendHoursPerProject>();
        }
    
        public int Id { get; set; }
        public double SumPerHour { get; set; }
        public double TotalHours { get; set; }
        public int UserId { get; set; }
        public int CurrencyId { get; set; }
        public string Name { get; set; }
        public bool IsEnded { get; set; }
    
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<other_FreelancePayement> other_FreelancePayement { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<other_SpendHoursPerProject> other_SpendHoursPerProject { get; set; }
    }
}
