//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAccountant.DataLayer.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class other_FreelancePayement
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public double HoursPayed { get; set; }
        public double SumPayed { get; set; }
        public System.DateTime PayDate { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual other_Projects other_Projects { get; set; }
    }
}
