//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAccountant.DataLayer.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PAccountantEntities : DbContext
    {
        public PAccountantEntities()
            : base("name=PAccountantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<OperationCategory> OperationCategories { get; set; }
        public virtual DbSet<OperationSource> OperationSources { get; set; }
        public virtual DbSet<OperationType> OperationTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<debt_DebtAgent> debt_DebtAgent { get; set; }
        public virtual DbSet<debt_Transactions> debt_Transactions { get; set; }
        public virtual DbSet<debt_DebtOperations> debt_DebtOperations { get; set; }
        public virtual DbSet<debt_DebtType> debt_DebtType { get; set; }
    }
}
